#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 16
bspc cpnfig bottom_padding 16

# Autostart

sxhkd & # | tee -a /tmp/sxhkd.log &
picom --backend glx -f --config $HOME/.config/picom/picom.conf & # | tee -a /tmp/picom.log &
nitrogen --restore & # | tee -a /tmp/nitrogen.log &
dunst & # | tee -a /tmp/dunst.log &
/home/chasyxx/.config/polybar/begin.sh &
alacritty &

feh --bg-scale /path/to/background/image.png &
